version: '3.9'
services:
  db:
    container_name: realworld-elixir-phoenix-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '54320:5432'
